# Uncomment the following lines to use the default Podfile for Flutter projects

platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
# Disable these analytics by adding the following line:
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Add the Flutter podspec
flutter_application_path = '../..'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end