name: Build Flutter Android Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: android-release
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      ANDROID_HOME: ${{ runner.temp }}/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: gradle

      - name: Set up Flutter (match your Dart SDK version)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7"   # Use the Flutter version compatible with Dart >=3.6.0
          channel: stable

      - name: Prepare Android SDK & NDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          curl -sS https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm /tmp/cmdline-tools.zip
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses || true
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;27.0.12077973" || true

      - name: Verify Java & Flutter versions
        run: |
          java -version
          flutter --version

      - name: Clean Gradle (if wrapper exists)
        working-directory: ./android
        run: |
          if [ -f gradlew ]; then
            ./gradlew --stop || true
            ./gradlew clean || true
          else
            echo "No gradlew in android/ — skipping cleanup"
          fi

      - name: Cache pub & Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build release APK
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: flutter build apk --release --no-shrink

      - name: Upload APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
