name: Build APK

on:
  push:
    branches: [ main, master ] # Adjust branch names if necessary (e.g., 'main')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Updated to v4 for better security

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17' # Use Java 17 which is common for recent Flutter versions

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x' # Use a stable 3.x version, or specify exact version like '3.24.0'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    # Optional: Run tests if your project has them
    # - name: Run tests
    #   run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Upload Release APK
      uses: actions/upload-artifact@v4 # Updated to v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
